[package]
name = "game"
edition = "2024"
version.workspace = true
depscription.workspace = true

[dependencies]
convenient_lib = { version = "1.0.0", path = "../convenient_lib" }
image = "0.25.10"
itertools = "0.14.0"
piston = "1.0.0"
piston_components = { version = "1.0.0", path = "../piston_components" }
piston_window = "0.146.0"
playground = { version = "1.0.0", path = "../playground" }
qlearning = { version = "1.0.0", path = "../qlearning" }
rand = "0.10.0"
serde = "1.0.228"
serde_json = "1.0.149"
vecmath = "1.0.0"
