[package]
name = "l2s"
edition = "2024"
version.workspace = true
depscription.workspace = true

[dependencies]
clap = { version = "4.6.0", features = ["cargo"] }
console = "0.16.3"
convenient_lib = { version = "0.1.0", path = "../convenient_lib" }
playground = { version = "0.1.0", path = "../playground" }
qlearning = { version = "0.1.0", path = "../qlearning" }
rand = "0.10.0"
