[package]
name = "qlearning"
edition = "2024"
version.workspace = true
depscription.workspace = true

[dependencies]
convenient_lib = { version = "1.0.0", path = "../convenient_lib" }
mathlib = { version = "1.0.0", path = "../mathlib" }
playground = { version = "1.0.0", path = "../playground" }
rand = "0.10.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
